services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nosana-backend
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
      - PORT=8000
    restart: unless-stopped
    networks:
      - nosana-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nosana-frontend
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - nosana-network

networks:
  nosana-network:
    driver: bridge
